# Generated by Django 5.1.1 on 2024-10-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_attendance_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='phonenumber',
            new_name='Name',
        ),
    ]
