# Generated by Django 5.1.1 on 2024-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_phonenumber_attendance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
